
#ifndef WORLDCONSTANTS_H
#define WORLDCONSTANTS_H
constexpr int CHUNK_SIZE = 16, CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE,
              CHUNK_VOLUME = CHUNK_SIZE * CHUNK_SIZE * CHUNK_SIZE, RADIUS=8, WATER_LEVEL = 60;

#endif // WORLDCONSTANTS_H